	; this line for VSCode proper formating
TILEDATA_NO_COLLISION	= 0
TILEDATA_COLLISION		= %11111111
TILEDATA_RESTORE_TILE	= 1
TILEDATA_COLLIDABLE		= 8*16
TILEDATA_BREAKABLE		= 13*16

TILEDATA_FUNC_MASK		= %11110000
TILEDATA_ARG_MASK		= %00001111

TILE_IDX_INVALID = $ff

TILEDATA_FUNC_ID_MONSTERS	= 1
TILEDATA_FUNC_ID_ITEMS		= 6
TILEDATA_FUNC_ID_RESOURCES	= 7
TILEDATA_FUNC_ID_TRIGGERS	= 10
TILEDATA_FUNC_ID_CONTAINERS	= 11
TILEDATA_FUNC_ID_DOORS		= 12
TILEDATA_FUNC_ID_BREAKABLES	= 13
TILEDATA_FUNC_ID_COLLISION	= 15

TILEDATA_STORYTELLING = 0
TIMEDATA_TRIGGER_HOME_DOOR			= 0
TIMEDATA_TRIGGER_FRIEND_DOOR		= 1
TIMEDATA_TRIGGER_DUNGEON_ENTRANCE	= 2

LEVELS_MAX	= 2
ROOMS_MAX	= 64

ROOM_WIDTH		= 16 ; in tiles
ROOM_HEIGHT		= 15 ; in tiles

TILE_WIDTH		= 16
TILE_WIDTH_B	= 2
TILE_HEIGHT		= 16

ROOM_TILEDATA_LEN	= ROOM_WIDTH * ROOM_HEIGHT

